### ISSUE TITLE
[Bug]: Argument #1 ($bytes) must be of type int|float, null given

### ISSUE THREAD

**Issue by dmitry-buzzwoo** [schmeits/pulse-database-table-info#10]
### What happened?

Got an error on null value:
![Screenshot 2024-11-04 at 19 34 53](https://github.com/user-attachments/assets/f04a531a-2e65-4e1d-b678-06ffb751dcd2)
![Screenshot 2024-11-04 at 19 35 01](https://github.com/user-attachments/assets/ff7b5475-7a24-4269-99c4-be17ac5365fd)

### How to reproduce the bug

Run with empty result size.

### Package Version

latest

### PHP Version

8.1

### Laravel Version

10

**Comment by dmitry-buzzwoo** [comment]
It tires to take the info from the view, which is empty. In this case throws exception. I think it should be 0 in the case it can't detect the size.
![Screenshot 2024-11-04 at 19 41 06](https://github.com/user-attachments/assets/64a96dea-6c24-46d7-8020-6d8eee8ff100)

**Comment by dmitry-buzzwoo** [comment]
![Screenshot 2024-11-04 at 19 42 49](https://github.com/user-attachments/assets/5d566e89-69bc-49cc-b76a-e1957d1cf2ce)

**Comment by schmeits** [comment]
Will add the fix shortly... thanks for reaching out

**Comment by schmeits** [comment]
Fixed in version 1.7.1
